name = "RadialCalderon"
uuid = "7c1695ff-6cb5-40f3-814e-ce6c04c192eb"
authors = ["Romain Petit <petitromain@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
